// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-1]
	_ = x[EOF-2]
	_ = x[LF-3]
	_ = x[Code-4]
	_ = x[Text-5]
	_ = x[TitleSpecial-6]
	_ = x[TripleDash-7]
	_ = x[Hash-8]
	_ = x[Pipe-9]
	_ = x[LBracket-10]
	_ = x[RBracket-11]
	_ = x[LBrace-12]
	_ = x[RBrace-13]
	_ = x[MediaOpen-14]
	_ = x[TripleQuote-15]
	_ = x[MetaOpen-16]
	_ = x[Equals-17]
}

const _TokenType_name = "IllegalEOFLFCodeTextTitleSpecialTripleDashHashPipeLBracketRBracketLBraceRBraceMediaOpenTripleQuoteMetaOpenEquals"

var _TokenType_index = [...]uint8{0, 7, 10, 12, 16, 20, 32, 42, 46, 50, 58, 66, 72, 78, 87, 98, 106, 112}

func (i TokenType) String() string {
	i -= 1
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
